apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: alpha
  labels:
    name: ubuntu-pod
spec:
  containers:
  - name: ubuntu-pod
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]