# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages directly
RUN pip install --no-cache-dir kubernetes minio

# Make port 80 available to the world outside this container
EXPOSE 80

# Run master.py when the container launches
CMD ["tail", "-f", "/dev/null"]