# Use the official Python base image
FROM python:3.9-slim

# Install kubectl and other dependencies
RUN apt-get update && apt-get install -y curl \
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/ \
    && apt-get clean

# Set the working directory
WORKDIR /app

# Install Python dependencies directly
RUN pip install --no-cache-dir flask flask_sqlalchemy werkzeug pyjwt minio kubernetes

# Copy the application code
COPY . .

# Expose the port Flask is running on
EXPOSE 5000

# Run the application
CMD ["tail", "-f", "/dev/null"]