apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      serviceAccountName: master-sa
      containers:
        - name: master-container
          image: thkarakos/master-image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: master-sa
  namespace: alpha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator-role
  namespace: alpha
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-role-binding
  namespace: alpha
subjects:
  - kind: ServiceAccount
    name: master-sa
    namespace: alpha
roleRef:
  kind: Role
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io