apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: alpha

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-app-role
  namespace: alpha
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "services", "serviceaccounts"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-rolebinding
  namespace: alpha
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: alpha
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io